-- DEVOLVE A DATA DE HOJE, COM ALGUMAS INFORMAÇÕES A MAIS
DELIMITER $$
CREATE PROCEDURE SP_GET_DATE_FORMATADO(
	OUT retorno VARCHAR(255)
)
BEGIN
	SELECT
		CONCAT(
			'DATA DE HOJE = ', ', ',
			DAYNAME(CURRENT_DATE()), ', ',
			DAY(CURRENT_DATE()), ', ',
			MONTHNAME(CURRENT_DATE()), ', ',
			YEAR(CURRENT_DATE())
		) INTO retorno;
END $$

CALL SP_GET_DATE_FORMATADO(@retorno);
SELECT @retorno;