-- PROCEDURE PARA CRIPTOGRAFAR A SENHA DE UM USUÁRIO A PARTIR DO ID INFORMADO
SELECT
	*
FROM usuario;

DELIMITER $$
CREATE PROCEDURE SP_CRIPTOGRAFA_SENHA(
	IN paramIdUsuario INT
)
BEGIN
	UPDATE
		usuario
	SET
		senha = MD5(senha)
	WHERE
		idUsuario = paramIdUsuario;
END $$

CALL SP_CRIPTOGRAFA_SENHA(1);