CREATE SCHEMA IF NOT EXISTS `AULA8` ;
USE `AULA8` ;

-- -----------------------------------------------------
-- Table `AULA8`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AULA8`.`PACIENTE` (
  `ID_PACIENTE` INT NOT NULL AUTO_INCREMENT,
  `NR_CARTEIRINHA` INT(11) NULL,
  `NOME` VARCHAR(150) NULL,
  `SOBRENOME` VARCHAR(150) NULL,
  PRIMARY KEY (`ID_PACIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AULA8`.`MEDICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AULA8`.`MEDICO` (
  `ID_MEDICO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(150) NULL,
  `SOBRENOME` VARCHAR(150) NULL,
  PRIMARY KEY (`ID_MEDICO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AULA8`.`CONSULTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AULA8`.`CONSULTA` (
  `ID_CONSULTA` INT NOT NULL AUTO_INCREMENT,
  `ID_PACIENTE` INT NULL,
  `ID_MEDICO` INT NULL,
  `DATA_HORA_CONSULTA` DATETIME NULL,
  PRIMARY KEY (`ID_CONSULTA`),
  INDEX `FK_CONSULTA_PACIENTE_idx` (`ID_PACIENTE` ASC) VISIBLE,
  INDEX `FK_CONSULTA_MEDICO_idx` (`ID_MEDICO` ASC) VISIBLE,
  CONSTRAINT `FK_CONSULTA_PACIENTE`
    FOREIGN KEY (`ID_PACIENTE`)
    REFERENCES `AULA8`.`PACIENTE` (`ID_PACIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CONSULTA_MEDICO`
    FOREIGN KEY (`ID_MEDICO`)
    REFERENCES `AULA8`.`MEDICO` (`ID_MEDICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AULA8`.`ESPECIALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AULA8`.`ESPECIALIDADE` (
  `ID_ESPECIALIDADE` INT NOT NULL AUTO_INCREMENT,
  `NOME_ESPECIALIDADE` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID_ESPECIALIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AULA8`.`MEDICO_ESPECIALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AULA8`.`MEDICO_ESPECIALIDADE` (
  `ID_MEDICO_ESPECIALIDADE` INT NOT NULL AUTO_INCREMENT,
  `ID_MEDICO` INT NULL,
  `ID_ESPECIALIDADE` INT NULL,
  PRIMARY KEY (`ID_MEDICO_ESPECIALIDADE`),
  INDEX `FK_MEDICO_ESPECIALIDADE_MEDICO_idx` (`ID_MEDICO` ASC) VISIBLE,
  INDEX `FK_MEDICO_ESPECIALIDADE_ESPECIALIDADE_idx` (`ID_ESPECIALIDADE` ASC) VISIBLE,
  CONSTRAINT `FK_MEDICO_ESPECIALIDADE_MEDICO`
    FOREIGN KEY (`ID_MEDICO`)
    REFERENCES `AULA8`.`MEDICO` (`ID_MEDICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MEDICO_ESPECIALIDADE_ESPECIALIDADE`
    FOREIGN KEY (`ID_ESPECIALIDADE`)
    REFERENCES `AULA8`.`ESPECIALIDADE` (`ID_ESPECIALIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
