CREATE DATABASE DHTUBE;
USE DHTUBE;

CREATE TABLE PAIS (
ID_PAIS INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL
);

CREATE TABLE AVATAR (
ID_AVATAR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45) NOT NULL,
URL_IMAGEM VARCHAR(100)
);

CREATE TABLE USUARIO (
ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_PAIS INT(11),
ID_AVATAR INT,
NOME VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
SENHA VARCHAR(45) NOT NULL,
DATA_NASCIMENTO DATETIME NOT NULL,
CEP VARCHAR(45),
CONSTRAINT FK_USUARIO_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS),
CONSTRAINT FK_USUARIO_AVATAR FOREIGN KEY (ID_AVATAR) REFERENCES AVATAR (ID_AVATAR)
);

CREATE TABLE CANAL (
ID_CANAL INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_USUARIO INT,
NOME VARCHAR(45) NOT NULL,
DESCRICAO TEXT,
DATA_CRIACAO DATETIME NOT NULL,
CONSTRAINT FK_CANAL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE VIDEO (
ID_VIDEO INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_USUARIO INT,
TITULO VARCHAR(100) NOT NULL,
DESCRICAO TEXT,
TAMANHO DOUBLE,
NOME_ARQUIVO VARCHAR(100),
DURACAO DOUBLE,
IMAGEM VARCHAR(100),
QTD_REPRODUCOES INT(11),
QTD_LIKES INT(11),
QTD_DISLIKES INT(11),
PRIVADO SMALLINT(6),
DATA_PUBLICACAO DATETIME,
CONSTRAINT FK_VIDEO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE PLAYLIST (
ID_PLAYLIST INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_USUARIO INT,
NOME VARCHAR(45) NOT NULL,
DATA_CRIACAO DATETIME,
PRIVADO SMALLINT(6),
CONSTRAINT FK_PLAYLIST_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE PLAYLIST_VIDEO (
ID_VIDEO INT(11),
ID_PLAYLIST INT(11),
CONSTRAINT FK_PLAYLIST_VIDEO_VIDEO FOREIGN KEY (ID_VIDEO) REFERENCES VIDEO (ID_VIDEO),
CONSTRAINT FK_PLAYLIST_VIDEO_ID_PLAYLIST FOREIGN KEY (ID_PLAYLIST) REFERENCES PLAYLIST (ID_PLAYLIST)
);
