-- Banco de dados para um sistema de assistência técnica, onde serão lançadas ordens de serviço. Tabelas com dados de cidades e clientes.
-- Nas ordens de serviço, poderá ser lançado serviços de mão de obra, atraves de itens de serviço e peças utilizadas atraves de produtos usados.
-- Foi criado ligação entre as tabelas para facilitar futuras consultas e cadastros no banco de dados, bem como emissão de relatórios gerenciais
-- dos atendimentos prestados.

CREATE DATABASE bd_checkpoint_2;
USE bd_checkpoint_2;

CREATE TABLE CIDADE (
ID_CIDADE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
CIDADE VARCHAR(100) NOT NULL,
UF VARCHAR(2) NOT NULL,
PAIS VARCHAR(100) NOT NULL
);

CREATE TABLE SERVICO (
ID_SERVICO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
DESCRICAO VARCHAR(200) NOT NULL,
VALOR DECIMAL(5,2) NOT NULL
);

CREATE TABLE PRODUTO (
ID_PRODUTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
VALOR DECIMAL(5,2) NOT NULL,
CUSTO DECIMAL(5,2),
ESTOQUEATUAL DECIMAL(5,1) NOT NULL
);

CREATE TABLE CLIENTE (
ID_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME_RAZAO VARCHAR(100) NOT NULL,
ENDERECO VARCHAR(200),
BAIRRO VARCHAR(100),
ID_CIDADE INT NOT NULL,
CEP VARCHAR(10),
CPF VARCHAR(15),
RG VARCHAR(15),
CNPJ VARCHAR(18),
IE VARCHAR(20),
TIPOPESSOA TINYINT,
CONSTRAINT FK_CLIENTE_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID_CIDADE)
);

CREATE TABLE ORDEMSERVICO (
ID_ORDEMSERVICO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
DATA_ENTRADA DATETIME NOT NULL,
PREVISAO_ENTREGA DATETIME,
ID_CLIENTE INT NOT NULL,
RESPONSAVEL VARCHAR(100) NOT NULL,
EQUIPAMENTO VARCHAR(200) NOT NULL,
DEFEITO VARCHAR(200) NOT NULL,
SITUACAO_ORDEM VARCHAR(100) NOT NULL,
TOTALSERVICO DECIMAL(5,2) NOT NULL,
TOTALPRODUTO DECIMAL(5,2) NOT NULL,
TOTALORDEM DECIMAL(5,2) NOT NULL,
DATAENTREGA DATETIME NOT NULL,
CONSTRAINT FK_ORDEMSERVICO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE ITEMSERVICO (
ID_ORDEMSERVICO INT NOT NULL,
ID_SERVICO INT NOT NULL,
QUANTIDADE INT NOT NULL,
VALOR DECIMAL(5,2),
CONSTRAINT FK_ITEMORDEM_ORDEMSERVICO FOREIGN KEY (ID_ORDEMSERVICO) REFERENCES ORDEMSERVICO (ID_ORDEMSERVICO),
CONSTRAINT FK_ITEMORDEM_SERVICO FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO (ID_SERVICO)
);

CREATE TABLE ITEMPRODUTO (
ID_ORDEMSERVICO INT NOT NULL,
ID_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
VALOR DECIMAL(5,2) NOT NULL,
CONSTRAINT FK_ITEMPRODUTO_ORDEMSERVICO FOREIGN KEY (ID_ORDEMSERVICO) REFERENCES ORDEMSERVICO (ID_ORDEMSERVICO),
CONSTRAINT FK_ITEMPRODUTO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);


