USE bd_checkpoint_2;

INSERT INTO cidade (ID_CIDADE, CIDADE, UF, PAIS)
	VALUES 	(DEFAULT, 'FLORES DA CUNHA', 'RS', 'BRASIL'),
			(DEFAULT, 'CAXIAS DO SUL', 'RS', 'BRASIL'),
			(DEFAULT, 'PORTO ALEGRE', 'RS', 'BRASIL'),
			(DEFAULT, 'GRAMADO', 'RS', 'BRASIL'),
			(DEFAULT, 'SAO PAULO', 'RS', 'BRASIL');

UPDATE cidade SET UF = 'SP' WHERE ID_CIDADE = 5;

DELETE FROM cidade WHERE ID_CIDADE = 5;

SELECT * FROM cidade;