-- MySQL Script generated by MySQL Workbench
-- Sun Nov 14 17:12:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_checkpoint_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_checkpoint_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_checkpoint_1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_checkpoint_1` ;

-- -----------------------------------------------------
-- Table `bd_checkpoint_1`.`CIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_checkpoint_1`.`CIDADE` (
  `ID_CIDADE` INT NOT NULL AUTO_INCREMENT,
  `CIDADE` VARCHAR(100) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `PAIS` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_CIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_checkpoint_1`.`SERVICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_checkpoint_1`.`SERVICO` (
  `ID_SERVICO` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(200) NOT NULL,
  `VALOR` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`ID_SERVICO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_checkpoint_1`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_checkpoint_1`.`PRODUTO` (
  `ID_PRODUTO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `VALOR` DECIMAL(5,2) NOT NULL,
  `CUSTO` DECIMAL(5,2) NULL,
  `ESTOQUEATUAL` DECIMAL(5,1) NOT NULL,
  PRIMARY KEY (`ID_PRODUTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_checkpoint_1`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_checkpoint_1`.`CLIENTE` (
  `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NOME_RAZAO` VARCHAR(100) NOT NULL,
  `ENDERECO` VARCHAR(200) NULL,
  `BAIRRO` VARCHAR(100) NULL,
  `ID_CIDADE` INT NOT NULL,
  `CEP` VARCHAR(10) NULL,
  `CPF` VARCHAR(15) NULL,
  `RG` VARCHAR(15) NULL,
  `CNPJ` VARCHAR(18) NULL,
  `IE` VARCHAR(20) NULL,
  `TPOPESSOA` TINYINT NULL,
  PRIMARY KEY (`ID_CLIENTE`),
  INDEX `FK_CLIENTE_CIDADE_idx` (`ID_CIDADE` ASC) VISIBLE,
  CONSTRAINT `FK_CLIENTE_CIDADE`
    FOREIGN KEY (`ID_CIDADE`)
    REFERENCES `bd_checkpoint_1`.`CIDADE` (`ID_CIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_checkpoint_1`.`ORDEMSERVICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_checkpoint_1`.`ORDEMSERVICO` (
  `ID_ORDEMSERVICO` INT NOT NULL AUTO_INCREMENT,
  `DATA_ENTRADA` DATETIME NOT NULL,
  `PREVISAO_ENTREGA` DATETIME NULL,
  `ID_CLIENTE` INT NOT NULL,
  `RESPONSAVEL` VARCHAR(100) NOT NULL,
  `EQUIPAMENTO` VARCHAR(200) NOT NULL,
  `DEFEITO` VARCHAR(200) NOT NULL,
  `SITUACAO_ORDEM` VARCHAR(100) NOT NULL,
  `TOTALSERVICO` DECIMAL(5,2) NOT NULL,
  `TOTALPRODUTO` DECIMAL(5,2) NOT NULL,
  `TOTALORDEM` DECIMAL(5,2) NOT NULL,
  `DATAENTREGA` DATETIME NOT NULL,
  PRIMARY KEY (`ID_ORDEMSERVICO`),
  INDEX `FK_ORDEMSERVICO_CLIENTE_idx` (`ID_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `FK_ORDEMSERVICO_CLIENTE`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `bd_checkpoint_1`.`CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_checkpoint_1`.`ITEMSERVICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_checkpoint_1`.`ITEMSERVICO` (
  `ID_ORDEMSERVICO` INT NOT NULL,
  `ID_SERVICO` INT NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  `VALOR` DECIMAL(5,2) NULL,
  INDEX `FK_ITEMORDEM_ORDEMSERVICO_idx` (`ID_ORDEMSERVICO` ASC) VISIBLE,
  INDEX `FK_ITEMORDEM_SERVICO_idx` (`ID_SERVICO` ASC) VISIBLE,
  CONSTRAINT `FK_ITEMORDEM_ORDEMSERVICO`
    FOREIGN KEY (`ID_ORDEMSERVICO`)
    REFERENCES `bd_checkpoint_1`.`ORDEMSERVICO` (`ID_ORDEMSERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ITEMORDEM_SERVICO`
    FOREIGN KEY (`ID_SERVICO`)
    REFERENCES `bd_checkpoint_1`.`SERVICO` (`ID_SERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_checkpoint_1`.`ITEMPRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_checkpoint_1`.`ITEMPRODUTO` (
  `ID_ORDEMSERVICO` INT NOT NULL,
  `ID_PRODUTO` INT NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  `VALOR` DECIMAL(5,2) NOT NULL,
  INDEX `FK_ITEMPRODUTO_ORDEMSERVICO_idx` (`ID_ORDEMSERVICO` ASC) VISIBLE,
  INDEX `FK_ITEMPRODUTO_PRODUTO_idx` (`ID_PRODUTO` ASC) VISIBLE,
  CONSTRAINT `FK_ITEMPRODUTO_ORDEMSERVICO`
    FOREIGN KEY (`ID_ORDEMSERVICO`)
    REFERENCES `bd_checkpoint_1`.`ORDEMSERVICO` (`ID_ORDEMSERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ITEMPRODUTO_PRODUTO`
    FOREIGN KEY (`ID_PRODUTO`)
    REFERENCES `bd_checkpoint_1`.`PRODUTO` (`ID_PRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
