let nome1 = ("José da Silva")
let idade1 = (27)
let peso1 = (83.5)
let altura1 = (1.7)
let plano1 = true
let imc1 = (peso1 / (altura1*altura1)).toFixed(2)
console.log(nome1 + " tem " + idade1 + " anos e seu índice de massa corporal é de " + imc1)
let nome2 = ("Carlos de Souza")
let idade2 = (28)
let peso2 = (80.1)
let altura2 = (1.76)
let plano2 = true
let imc2 = (peso2 / (altura2*altura2)).toFixed(2)
console.log(nome2 + " tem " + idade2 + " anos e seu índice de massa corporal é de " + imc2)
let nome3 = ("Aline Ferreira")
let idade3 = (33)
let peso3 = (63.7)
let altura3 = (1.53)
let plano3 = false
let imc3 = (peso3 / (altura3*altura3)).toFixed(2)
console.log(nome3 + " tem " + idade3 + " anos e seu índice de massa corporal é de " + imc3)
let nome4 = ("Ana Paula")
let idade4 = (26)
let peso4 = (55)
let altura4 = (1.62)
let plano4 = true
let imc4 = (peso4 / (altura4*altura4)).toFixed(2)
console.log(nome4 + " tem " + idade4 + " anos e seu índice de massa corporal é de " + imc4)
let nome5 = ("Elissandro Maciel")
let idade5 = (41)
let peso5 = (96.5)
let altura5 = (1.69)
let plano5 = true
let imc5 = (peso5 / (altura5*altura5)).toFixed(2)
console.log(nome5 + " tem " + idade5 + " anos e seu índice de massa corporal é de " + imc5)
